In [58]:
# Imports as always...
import numpy as np
from fpylll import IntegerMatrix, LLL, GSO
from copy import deepcopy
import cirq
import sympy
import qsimcirq
from scipy.optimize import minimize

# Time keeping.
import time

# Ignore warnings.
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Bunch of primes.
primes = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997,1009,1013,1019,1021,1031,1033,1039,1049,1051,1061,1063,1069,1087,1091,1093,1097,1103,1109,1117,1123,1129,1151,1153,1163,1171,1181,1187,1193,1201,1213,1217,1223,1229,1231,1237,1249,1259,1277,1279,1283,1289,1291,1297,1301,1303,1307,1319,1321,1327,1361,1367,1373,1381,1399,1409,1423,1427,1429,1433,1439,1447,1451,1453,1459,1471,1481,1483,1487,1489,1493,1499,1511,1523,1531,1543,1549,1553,1559,1567,1571,1579,1583,1597,1601,1607,1609,1613,1619,1621,1627,1637,1657,1663,1667,1669,1693,1697,1699,1709,1721,1723,1733,1741,1747,1753,1759,1777,1783,1787,1789,1801,1811,1823,1831,1847,1861,1867,1871,1873,1877,1879,1889,1901,1907,1913,1931,1933,1949,1951,1973,1979,1987,1993,1997,1999,2003,2011,2017,2027,2029,2039,2053,2063,2069,2081,2083,2087,2089,2099,2111,2113,2129,2131,2137,2141,2143,2153,2161,2179,2203,2207,2213,2221,2237,2239,2243,2251,2267,2269,2273,2281,2287,2293,2297,2309,2311,2333,2339,2341,2347,2351,2357,2371,2377,2381,2383,2389,2393,2399,2411,2417,2423,2437,2441,2447,2459,2467,2473,2477,2503,2521,2531,2539,2543,2549,2551,2557,2579,2591,2593,2609,2617,2621,2633,2647,2657,2659,2663,2671,2677,2683,2687,2689,2693,2699,2707,2711,2713,2719,2729,2731,2741,2749,2753,2767,2777,2789,2791,2797,2801,2803,2819,2833,2837,2843,2851,2857,2861,2879,2887,2897,2903,2909,2917,2927,2939,2953,2957,2963,2969,2971,2999,3001,3011,3019,3023,3037,3041,3049,3061,3067,3079,3083,3089,3109,3119,3121,3137,3163,3167,3169,3181,3187,3191,3203,3209,3217,3221,3229,3251,3253,3257,3259,3271,3299,3301,3307,3313,3319,3323,3329,3331,3343,3347,3359,3361,3371,3373,3389,3391,3407,3413,3433,3449,3457,3461,3463,3467,3469,3491,3499,3511,3517,3527,3529,3533,3539,3541,3547,3557,3559,3571,3581,3583,3593,3607,3613,3617,3623,3631,3637,3643,3659,3671,3673,3677,3691,3697,3701,3709,3719,3727,3733,3739,3761,3767,3769,3779,3793,3797,3803,3821,3823,3833,3847,3851,3853,3863,3877,3881,3889,3907,3911,3917,3919,3923,3929,3931,3943,3947,3967,3989,4001,4003,4007,4013,4019,4021,4027,4049,4051,4057,4073,4079,4091,4093,4099,4111,4127,4129,4133,4139,4153,4157,4159,4177,4201,4211,4217,4219,4229,4231,4241,4243,4253,4259,4261,4271,4273,4283,4289,4297,4327,4337,4339,4349,4357,4363,4373,4391,4397,4409,4421,4423,4441,4447,4451,4457,4463,4481,4483,4493,4507,4513,4517,4519,4523,4547,4549,4561,4567,4583,4591,4597,4603,4621,4637,4639,4643,4649,4651,4657,4663,4673,4679,4691,4703,4721,4723,4729,4733,4751,4759,4783,4787,4789,4793,4799,4801,4813,4817,4831,4861,4871,4877,4889,4903,4909,4919,4931,4933,4937,4943,4951,4957,4967,4969,4973,4987,4993,4999,5003,5009,5011,5021,5023,5039,5051,5059,5077,5081,5087,5099,5101,5107,5113,5119,5147,5153,5167,5171,5179,5189,5197,5209,5227,5231,5233,5237,5261,5273,5279,5281,5297,5303,5309,5323,5333,5347,5351,5381,5387,5393,5399,5407,5413,5417,5419,5431,5437,5441,5443,5449,5471,5477,5479,5483,5501,5503,5507,5519,5521,5527,5531,5557,5563,5569,5573,5581,5591,5623,5639,5641,5647,5651,5653,5657,5659,5669,5683,5689,5693,5701,5711,5717,5737,5741,5743,5749,5779,5783,5791,5801,5807,5813,5821,5827,5839,5843,5849,5851,5857,5861,5867,5869,5879,5881,5897,5903,5923,5927,5939,5953,5981,5987,6007,6011,6029,6037,6043,6047,6053,6067,6073,6079,6089,6091,6101,6113,6121,6131,6133,6143,6151,6163,6173,6197,6199,6203,6211,6217,6221,6229,6247,6257,6263,6269,6271,6277,6287,6299,6301,6311,6317,6323,6329,6337,6343,6353,6359,6361,6367,6373,6379,6389,6397,6421,6427,6449,6451,6469,6473,6481,6491,6521,6529,6547,6551,6553,6563,6569,6571,6577,6581,6599,6607,6619,6637,6653,6659,6661,6673,6679,6689,6691,6701,6703,6709,6719,6733,6737,6761,6763,6779,6781,6791,6793,6803,6823,6827,6829,6833,6841,6857,6863,6869,6871,6883,6899,6907,6911,6917,6947,6949,6959,6961,6967,6971,6977,6983,6991,6997,7001,7013,7019,7027,7039,7043,7057,7069,7079,7103,7109,7121,7127,7129,7151,7159,7177,7187,7193,7207,7211,7213,7219,7229,7237,7243,7247,7253,7283,7297,7307,7309,7321,7331,7333,7349,7351,7369,7393,7411,7417,7433,7451,7457,7459,7477,7481,7487,7489,7499,7507,7517,7523,7529,7537,7541,7547,7549,7559,7561,7573,7577,7583,7589,7591,7603,7607,7621,7639,7643,7649,7669,7673,7681,7687,7691,7699,7703,7717,7723,7727,7741,7753,7757,7759,7789,7793,7817,7823,7829,7841,7853,7867,7873,7877,7879,7883,7901,7907,7919]

We have a semi-prime $N$, of bit-length $m=\log_2(N)$, that we would like to factor using a hybrid quantum-classical adaptation of Shnorr's sieve-based factoring algorithm.

By the claims of Yan et al. (2022), carried over from Schnorr (2021), which have been refuted both theoretically and (in Schnorr's case) empircally debated, we may reduce the problem of integer factorisation a CVP on a prime lattice of dimension $n\sim O(m/\log_2 m)$.

In [55]:
# Problem setup...

# Semi-prime to be factored.
N = 48567227

# Precision parameter
c = 4

# Lattice parameter.
l = 1

# Seed for random state.
seed = 99
np.random.seed(seed)

# Bit-length and Lattice dimension.
m = np.round(np.log2(N)).astype(int)
n = np.round(l * m // np.log2(m)).astype(int)

# Smooth bound to consider sr-pairs under.
# As far as I can tell, Yan et al. (2022) arbitrarily set this as n^2.
smooth_bound = n ** 2

print(f'Factoring N = {N}\nwith precision parameter (c): 4 and lattice parameter (l): 1\n')
print(f'Bit-length (m): {m}\nLattice dimension (n): {n}\nSmooth bound: {smooth_bound}')

Factoring N = 48567227
with precision parameter (c): 4 and lattice parameter (l): 1

Bit-length (m): 26
Lattice dimension (n): 5
Smooth bound: 25


### 1. Setting up the CVP

We first define the prime lattice $B_{n,c}$ and a target vector $t$, giving us our CVP (i.e. the reduction of the factorisation of $N$, with an intermediary step of finding smooth-relation pairs).

In [56]:
def generate_cvp(N, n, c):
    """
    Generate a random instance of the CVP reducing the problem of factorisation of N.

    :param N: Semi-prime to be factored.
    :param n: Lattice dimension.
    :param c: "Precision parameter".
    :param seed: Seed for random state generation.

    :return: Prime lattice's basis matrix (B), and a target vector (t).
    """

    # Produce the random permutation for the diagonal.
    f = np.random.permutation([(i + 1) // 2 for i in range(1, n + 1)])

    # Create a zero matrix and add in the diagonal permutation.
    B = np.zeros(shape=(n, n))
    np.fill_diagonal(B, f)

    # Create the extra final row and stick it on.
    final_row = np.round(10 ** c * np.log(np.array(primes[:n])))
    B = np.vstack((B, final_row))

    # fpylll doesn't like numyp arrays, so convert it to a stnadard array.
    B = [[int(b) for b in bs] for bs in B]

    # Convert B to a matrix of integers (in fpylll's own type).
    B = IntegerMatrix.from_matrix(B)

    # Define the target vector.
    t = np.zeros(n + 1)
    t[-1] = np.round(10 ** c * np.log(N))
    t = tuple(t.astype(int))

    return B, t

B, t = generate_cvp(N, n, c)

print(f'B = \n{B}\n')
print(f't = \n{t}\n')

B = 
[    2     0     0     0     0 ]
[    0     1     0     0     0 ]
[    0     0     3     0     0 ]
[    0     0     0     2     0 ]
[    0     0     0     0     1 ]
[ 6931 10986 16094 19459 23979 ]

t = 
(0, 0, 0, 0, 0, 176985)



### 2. A classical approximation to the CVP

Next we run Babai's algorithm to find an approximate closest vector $b_{op}$ to the target vector $t$.

Babai's algorithm works by finding a reduced basis $D$ for the lattice (e.g. by LLL-reduction) and corresponding Gram-Schmidt orthogonal basis $\tilde(D)$, performing a "size-reduction" of $t$ using $D$, and yielding a solution $b_{op}=\sum_{i=1}^{n}c_id_i$, where the coefficient $c_i=\lceil\mu_i\rfloor=\lceil\langle d_i,\tilde{d}_i\rangle/\langle\tilde{d}_i,\tilde{d}_i\rangle\rfloor$ is obtained by rounding to the nearest integer to the Gram-Schmidt coefficient $\mu_i$.

In [5]:
# Helper function.
def integer_matrix_to_numpy(M):
    """
    Convert an fyplll.IntegerMatrix object to a numpy.ndarray object.

    :param M: fpylll.IntegerMatrix.

    :return: The same matrix (M) cast to a numpy ndarray.
    """

    m, n = M.nrows, M.ncols
    D = np.zeros((m, n), dtype=int)
    M.to_matrix(D)
    return D

def find_b_op(B, t, delta=.75):
    """
    Find an approximate solution to the CVP classically. We do this via Babai's algorithm with LLL-reduction.

    :param B: Prime basis (fpylll.IntegerMatrix object).
    :param t: Target vector (tuple of integers).
    :param delta: Hyperparameter for LLL-reduction (Wikipedia recommends .75, as do Yan et al. (2022)).
    
    :return: The given B and t, the reduced basis (D) and weights (w), the approximate solution (b_op = D*w), the residual vector (b_op - t), and the step signs (for use in the Hamiltonian later on).
    """

    # Create a copy of the prime basis and reduce it by LLL-reduction.
    D = deepcopy(B).transpose()
    LLL.reduction(D, delta)

    # Use a Gram-Schmidt orthogonalisation matrix object to run Babai's algorithm.
    M = GSO.Mat(D, update=True)
    w = M.babai(t)

    # We want to make a note of rounding directions (by comparing coefficients).
    A = IntegerMatrix(2 * D.nrows, D.ncols)
    for i in range(D.nrows):
        for j in range(D.ncols):
            A[i, j] = D[i, j]

    b = np.array(t)
    for i in reversed(range(D.nrows)):
        for j in range(D.ncols):
            A[i + D.nrows, j] = int(b[j])
        b -= w[i] * np.array(D[i])

    # Go through and make the comparisons to track which way each Gram-Schmidt coefficient (mu) was rounded.
    M = GSO.Mat(A, update=True)
    rounding_direction = []
    for i in range(D.nrows):
        mu = M.get_mu(i + D.nrows, i)
        rounding_direction.append(w[i] > mu)

    b_op = np.array(D.multiply_left(w))
    residual_vector = b_op - np.array(t)

    # Reformat the reduced basis.
    D = integer_matrix_to_numpy(D.transpose())

    # Convert the notes of rounding directions into "step signs", establishing the sign for each operator.
    step_signs = - (np.array(rounding_direction).astype(int) * 2 - 1)

    return D, w, b_op, residual_vector, step_signs

D, w, b_op, residual_vector, step_signs = find_b_op(B, t, delta=.75)

print(f'D = \n{D}\n')
print(f'w = \n{w}\n')
print(f'b_op = \n{b_op}\n')
print(f'residual_vector = \n{residual_vector}\n')
print(f'step_signs = \n{step_signs}\n')

D = 
[[  6  -8   2  -4  -4]
 [ -4  -3  11  -5  -3]
 [  6   6   3   0  -3]
 [  4  -2   0  12   4]
 [ -2   2  -6  -2   1]
 [ -3   5  -3   4 -17]]

w = 
(-3092, -354, -1837, 3883, -8732)

b_op = 
[     2      4      9      8      0 176993]

residual_vector = 
[2 4 9 8 0 8]

step_signs = 
[-1 -1 -1 -1  1]



### 3. Constructing an all-to-all Ising spin Hamiltonian

We are looking for a vector $v_{new}$ in the unit hypercube around Babai's solution $b_{op}$ that is closest to the target vector $t$; that is, we have an optimisation problem $F:\{\pm1,0\}^{n}\to\mathbb{R}$ defined by
\begin{split}
    F(z_1,\dots,z_n)=\|t-v_{new}\|^2&=\Bigg\|t-b_{op}-\sum_{i=1}^nz_id_i\Bigg\|^2\\&=\Bigg\|t-\sum_{i=1}^n(c_i+z_i)d_i\Bigg\|^2\ .
\end{split}

This can be mapped to the Hamiltonian
\begin{split}
    H_P&=\Bigg\|t-b_{op}+\sum_{i=1}^n\lceil\mu_i-c_i\rceil\hat{z}_id_i\Bigg\|^2\\&=\sum_{j=1}^{n+1}\Bigg|t_j-b^j_{op}+\sum_{i=1}^n\lceil\mu_i-c_i\rceil\hat{z}_id_{i,j}\Bigg|^2\ ,
\end{split}
where $\sigma_z^i$ denotes the Pauli-$Z$ operator $|0\rangle\langle0|-|1\rangle\langle1|$ acting on the $i$-th qubit.

In [6]:
def define_hamiltonian(D, residual_vector, step_signs):
    """
    Define the Hamiltonian using the unit hypercube search as outlined in Yan et al. (2022).

    :param D: The reduced (prime) basis.
    :param residual_vector: The discrepancy between the approximate solution and the target vector (b_op - t).
    :param step_signs: The signs for each operator.
    :param verbose: Whether to display messages during the computation.
    
    :return: The Hamiltonian (H).
    """

    # Define the circuit.
    circuit = cirq.LineQubit.range(D.shape[0])

    # Add the appropriate operator to each qubit.
    operators = []
    for i, sign in zip(circuit, step_signs):
        operator = sign * ((cirq.I(i) + -cirq.Z(i)) / 2)
        operators.append(operator)

    # Define the Hamiltonian.
    H = cirq.PauliSum()
    for j in range(D.shape[0]):
        h = residual_vector[j]
        for i in range(D.shape[1]):
            h += operators[i] * D[j, i]
        H += h ** 2

    return H

H = define_hamiltonian(D, residual_vector, step_signs)

# Pretty printing the Hamiltonian.
string_H = str(H)
string_H = string_H.replace('+', '\n+')
string_H = string_H.replace('-', '\n-')
string_H = string_H.replace('*', ' * ')
print(f'H = \n{string_H}\n')

H = 
292.000 * I
+3.500 * Z(q(0)) * Z(q(2))
+18.000 * Z(q(0)) * Z(q(3))
-17.500 * Z(q(0)) * Z(q(4))
-32.000 * Z(q(1))
+16.000 * Z(q(2))
-4.000 * Z(q(3))
-33.500 * Z(q(4))
-29.000 * Z(q(1)) * Z(q(2))
+19.500 * Z(q(1)) * Z(q(3))
+34.000 * Z(q(1)) * Z(q(4))
-31.500 * Z(q(2)) * Z(q(3))
+2.500 * Z(q(2)) * Z(q(4))
-4.500 * Z(q(3)) * Z(q(4))
+9.000 * Z(q(0))
-13.500 * Z(q(0)) * Z(q(1))



### 4. Sampling low-energy eigenstates

In QAOA, we are first opening up a uniform superposition over $n$ qubits via a Walsh-Hadamard transform $H^{\otimes n}|0^n\rangle$, then acting with the unitary $U(\gamma,H_P)=e^{-i\gamma H_P}$ parameterised by $\gamma$ and the unitary $U(\beta,B)=e^{i\pi\beta B/2}=\prod_{i=1}^ne^{i\pi\beta X_i/2}$ parameterised by $\beta$. Since this operation is not diagonal, there will be constructive and destructive interference that we hope will lead to states corresponding to low energy values for $H_P$.

In [7]:
# Helper functions.
def generate_gamma_layer(H, i):
    """
    Generate the i-th gamma layer executing the unitary exp(-i * gamma * H).

    :param H: The Hamiltonian.
    :param i: Layer index.
    
    :return: [] of cirq.DensePauliString object corresponding to the i-th gamma layer in the QAOA circuit.
    """

    # Gamma symbol placeholder.
    gamma = sympy.Symbol(f'gamma_{i}')

    # Instantiate the DensePauliString operators.
    dense_I = cirq.DensePauliString('')
    dense_Z = cirq.DensePauliString('Z')
    dense_ZZ = cirq.DensePauliString('ZZ')

    # Consider the terms in the Hamiltonian.
    for term in H:
        # Split the term into its coefficient and operator.
        coefficient = term.coefficient
        operator = term.with_coefficient(1).gate

        # Map to the appropriate circuit element on the basis of the operator, parameterised by gamma.
        if operator == dense_ZZ:
            yield cirq.ZZ(*term.qubits) ** (gamma * coefficient)
        elif operator == dense_Z:
            yield cirq.Z(*term.qubits) ** (gamma * coefficient)
        elif operator == dense_I:
            yield []
        else:
            raise Exception(f'Unrecognised Pauli string term {term} in the Hamiltonian.')

def generate_beta_layer(qubits, i):
    """
    Generate the i-th beta layer, executing a Pauli-X raised to beta across the given qubits.

    :param qubits: The qubits in the circuit.
    :param i: Layer index.
    
    :return: [] of cirq.DensePauliString object corresponding to the i-th beta layer in the QAOA circuit.
    """

    # Beta symbol placeholder.
    beta = sympy.Symbol(f'beta_{i}')

    # The layer is trivially defined by NOT gates parameterised by beta.
    return [cirq.X(q) ** beta for q in qubits]

def generate_qaoa_circuit(H, p=1):
    """
    Generate a QAOA circuit for the given Hamiltonian with a given depth.

    :param H: The Hamiltonian.
    :param p: Depth of the circuit (should be kept relatively small -- say 1 to 5).
    :param verbose: Whether to display messages during the computation.
    :return: cirq.Circuit object performing QAOA with the given Hamiltonian p times (depth p).
    """

    # Number of qubits.
    qubits = H.qubits

    # Define the circuit.
    return cirq.Circuit(
        # Hadamard over all qubits first to open uniform superposition.
        cirq.H.on_each(*qubits),

        # p layer of QAOA-ness.
        [
            (
                # Gamma layer.
                generate_gamma_layer(H, i),

                # Beta layer.
                generate_beta_layer(qubits, i)
            )
            for i in range(p)
        ]
    )

circuit = generate_qaoa_circuit(H, p=1)

print(circuit)

          ┌─────────────────────────────────┐   ┌─────────────────────────────────┐   ┌────────────────────────────────────┐                       ┌───────────────────────────────────┐
0: ───H────ZZ────────────────────────────────────ZZ────────────────────────────────────ZZ──────────────────────────────────────Z^(9.0*gamma_0)─────────────────────────────────────────────ZZ───────────────────X^beta_0───────────────────────
           │                                     │                                     │                                                                                                   │
1: ───H────┼───────────────Z^(-32.0*gamma_0)─────┼─────────────────────────────────────┼─────────────────ZZ────────────────────ZZ───────────────────ZZ─────────────────────────────────────ZZ^(-13.5*gamma_0)───X^beta_0───────────────────────
           │                                     │                                     │                 │                     │                  

In [11]:
def find_optimal_parameters(circuit, H, min_method='Nelder-Mead'):
    """
    Find the optimal assignments over the parameters in the given circuit.
    
    :param circuit: The QAOA circuit.
    :param H: The Hamiltonian.
    :return: cirq.ParamResolver object assigning values to each placeholder parameter in the given circuit.
    """
    
    # Define the parameters and observables.
    parameters = sorted(cirq.parameter_names(circuit))
    observables = [term.with_coefficient(1) for term in H]
    
    # Define the function to be minimised -- the expectation value with given assignments.
    def func_to_minimise(x):
        # Assign the parameters their given values.
        parameter_assignments = cirq.ParamResolver({param : val for param, val in zip(parameters, x)})
        
        # Simulator object.
        simulator = qsimcirq.QSimSimulator(
            qsimcirq.QSimOptions(cpu_threads=8, verbosity=0)
        )
        
        # Simulate the expectation value.
        result = simulator.simulate_expectation_values(
            program=circuit, observables=observables, param_resolver=parameter_assignments
        )
        
        # Compute the return, ignoring the imaginary component.
        return sum(term.coefficient * val for term, val in zip(H, result)).real
    
    # Initialise the assignments (with no prior knowledge, all zeros is fine).
    x0 = np.asarray([0.0] * len(parameters))
    
    # Minimise the function over the parameters.
    result = minimize(func_to_minimise, x0, method=min_method)
    return cirq.ParamResolver({param: optimal_val for param, optimal_val in zip(parameters, result.x)})

optimal_parameters = find_optimal_parameters(circuit, H, min_method='Nelder-Mead')

print(optimal_parameters.param_dict)

{'beta_0': -0.2438818364883828, 'gamma_0': 0.006395212065552549}


In [20]:
def sample_bitstring_from_parameters(circuit, parameter_assignments, H, repetitions):
    """
    Sample the states obtained via measurements made on the circuit with the given parameter assignments, given as a histogram of repeated runs.
    
    :param circuit: The circuit to measure.
    :param parameter_assignments: The assignments to the parameters (as a cirq.ParamResolver object).
    :param H: The Hamiltonian (whose qubits are operated on).
    :param repetitions: Number of times to repeat the sampling.
    :return: Histogram of states sampled by the measurements.
    """
    
    # Simulator object.
    simulator = qsimcirq.QSimSimulator(
        qsimcirq.QSimOptions(cpu_threads=8, verbosity=0)
    )
    
    # Add a set of measurement operators to the circuit.
    measurement_circuit = circuit + cirq.Circuit(cirq.measure(H.qubits, key='m'))
    
    # Run the simulation.
    result = simulator.run(measurement_circuit, param_resolver=parameter_assignments, repetitions=repetitions)
    
    # Let's have a histogram.
    return result.histogram(key='m')

states_histogram = sample_bitstring_from_parameters(circuit, optimal_parameters, H, repetitions=10000)
outcomes, frequencies = zip(*states_histogram.most_common(len(states_histogram)))

for state, freq in zip(outcomes, frequencies):
    print(f'{state:2d} (freq: {freq:4d})')

28 (freq: 1058)
 6 (freq: 1017)
17 (freq:  974)
23 (freq:  709)
14 (freq:  680)
 0 (freq:  659)
16 (freq:  632)
24 (freq:  593)
 7 (freq:  508)
30 (freq:  501)
 2 (freq:  439)
12 (freq:  370)
 3 (freq:  261)
19 (freq:  257)
22 (freq:  216)
29 (freq:  180)
21 (freq:  172)
 1 (freq:  171)
 8 (freq:  131)
20 (freq:   87)
18 (freq:   84)
31 (freq:   74)
 4 (freq:   57)
11 (freq:   53)
 9 (freq:   29)
27 (freq:   28)
25 (freq:   21)
15 (freq:   12)
 5 (freq:    9)
10 (freq:    9)
26 (freq:    7)
13 (freq:    2)


### 5. Outcomes to sr-pairs

We must now post-process our found solutions to the CVP as found sr-pairs.

In [31]:
def integer_outcomes_to_lattice_vectors(m, states, w, D, step_signs):
    """
    Convert states of integer outcomes to lattice vectors on the given prime lattice.
    """

    # Convert the integer state to a binary state -- telling us WHETHER to step in each basis direction.
    binary_states = (((states[:, None] & (1 << np.arange(m)[::-1]))) > 0).astype(int)
    
    # Pairwise-multiply the binary states and step signs -- telling us HOW to step in each basis.
    steps = np.multiply(binary_states, step_signs)
    
    # Add the steps to the Babai weights.
    w_new = w + steps
    
    # Left-multiply to yield the new vector v_new on the lattice corresponding to the states.
    return w_new @ D.T

lattice_vectors = integer_outcomes_to_lattice_vectors(n, np.asarray(outcomes), w, D, step_signs)

print(lattice_vectors)

[[     2      0     -6      6      6 176994]
 [     4     -2      6     -4      8 176992]
 [    -8      5      0      8      3 176979]
 [    -6     -1     -3     -4     11 176978]
 [    12      1      0     -2      6 176987]
 [     2      4      9      8      0 176993]
 [    -4      8      3      4      2 176996]
 [     4     11     -3      6      0 176991]
 [     0     -5      3      0      9 176975]
 [     6      5     -6     -6      8 176990]
 [     6      9      9     -4      2 176989]
 [     8     -4      0     10      4 176991]
 [     2      6      6      0      3 176972]
 [    -4     10      0     -4      5 176975]
 [    -2      2      0     -8     10 176995]
 [    -2     -3     -9     10      7 176977]
 [   -10     -6     -3      8      9 176982]
 [    -2      1      6     12      1 176976]
 [    10      7      3     10     -2 176988]
 [    -6     -3      0      4      8 176999]
 [     0     13      3     -8      4 176992]
 [     2      2     -9     -2      9 176973]
 [     0  

In [34]:
def lattice_vectors_to_u_v_pairs(lattice_vectors, B):
    """
    Reduce a set of lattice vectors to a set of u, v pairs.

    :param lattice_vectors: numpy.ndarray of lattice vectors.
    :param B: (numpy.ndarray) The basis matrix of the prime lattice. 
    """

    # Compute the pseudo-inverse of the prime lattice's basis matrix.
    B_pinv = np.linalg.pinv(np.asarray(B, dtype=int))

    # Left-multiply the lattice vectors by this pseudo-inverse to yield the prime expnents.
    # Round these to the nearest integer (integer pairs only!).
    prime_exponents = np.rint(lattice_vectors @ B_pinv.T).astype(int)

    # Find the smooth pairs corresponding to these exponents.
    first_n_primes = primes[:prime_exponents.shape[1]]
    u_exp = np.multiply(prime_exponents, (prime_exponents > 0).astype(int))
    v_exp = np.multiply(-prime_exponents, (prime_exponents < 0).astype(int))
    u = np.prod(np.power(first_n_primes, u_exp), axis=1)
    v = np.prod(np.power(first_n_primes, v_exp), axis=1)

    return np.stack((u, v), axis=-1)

u_v_pairs = lattice_vectors_to_u_v_pairs(lattice_vectors, integer_matrix_to_numpy(B))

print(u_v_pairs)

[[    1215290846             25]
 [   21435888100            441]
 [     776562633             16]
 [  285311670611           5880]
 [     340139712              7]
 [      48620250              1]
 [     194500845              4]
 [     243045684              5]
 [   11789738455            243]
 [  416713664664           8575]
 [    2381643000             49]
 [    3937140592             81]
 [      48514950              1]
 [    9509900499            196]
 [  233436821409           4802]
 [  327520882997           6750]
 [ 5661432406091         116640]
 [      97060425              2]
 [    5881105440            121]
 [   10503585169            216]
 [  116712415215           2401]
 [   42443058438            875]
 [  106337949025           2187]
 [      48498912              1]
 [     533655864             11]
 [    8488175652            175]
 [    1212977997             25]
 [    2182563152             45]
 [11463230904895         236196]
 [     340122240              7]
 [   83338

In [38]:
# Helper function.
def is_smooth(x, smooth_bound):
    first_n_primes = primes[:smooth_bound]

    for p in first_n_primes:
        while x % p == 0:
            x //= p

    return x == 1

def u_v_pairs_to_sr_pairs(u_v_pairs, N, smooth_bound):
    """
    Reduce a set of u, v pairs into smooth-relation pairs below a given smooth bound.
    
    :param u_v_pairs: numpy.ndarray of u, v pairs.
    :param N: Semi-prime to be factored.
    :param smooth_bound: The smooth bound (for alpha = 1, the lattice dimension).
    """
    
    # Give back the u, v pairs that form smooth-relation pairs under the given smooth bound.
    return [
        tuple(u_v) 
        for u_v in u_v_pairs
        if is_smooth(
            # | u - N*v | must be p_n-smooth, for given smooth bound p_n.
            abs(int(u_v[0]) - N * int(u_v[1])), smooth_bound
        )
    ]

found_sr_pairs = u_v_pairs_to_sr_pairs(u_v_pairs, N, smooth_bound)

print(found_sr_pairs)

[(11789738455, 243)]


# Considering the Full Loop to Produce sr-pairs

In [41]:
# Additional imports for keeping a set of sr-pairs.
from typing import Set, Tuple

In [73]:
# Problem setup...

# Semi-prime to be factored.
N = 48567227

# Precision parameter
c = 4

# Lattice parameter.
l = 1

# Seed for random state.
seed = 99
np.random.seed(seed)

# Bit-length and Lattice dimension.
m = np.round(np.log2(N)).astype(int)
n = np.round(l * m // np.log2(m)).astype(int)

# Smooth bound to consider sr-pairs under.
# As far as I can tell, Yan et al. (2022) arbitrarily set this as n^2.
smooth_bound = 2 * n ** 2

print(f'Factoring N = {N}\nwith precision parameter (c): 4 and lattice parameter (l): 1\n')
print(f'Bit-length (m): {m}\nLattice dimension (n): {n}\nSmooth bound: {smooth_bound}\n')

# ---

# Maximum number of iterations.
max_iterations = 1000

# Number of sr-pairs needed.
num_sr_pairs_needed = smooth_bound + 2

# Set of pairs collected.
sr_pairs: Set[Tuple[int, int]] = set()

# Algorithm parameters.
delta = .99
p = 1

# ---

# Main SQIF algorithm loop.
current_iteration = 0
while len(sr_pairs) < num_sr_pairs_needed and current_iteration < max_iterations:
    current_iteration += 1

    start_time = time.time_ns()

    # 1. Setting up the CVP...
    B, t = generate_cvp(N, n, c)

    # 2. A classical approximation to the CVP...
    D, w, b_op, residual_vector, step_signs = find_b_op(B, t, delta)

    # 3. Constructing an all-to-all Ising-spin Hamiltonian...
    H = define_hamiltonian(D, residual_vector, step_signs)

    # 4. Sampling low-energy eigenstates...
    circuit = generate_qaoa_circuit(H, p)

    # 5. Outcomes to sr-pairs...
    lattice_vectors = integer_outcomes_to_lattice_vectors(n, np.asarray(outcomes), w, D, step_signs)
    u_v_pairs = lattice_vectors_to_u_v_pairs(lattice_vectors, integer_matrix_to_numpy(B))
    found_sr_pairs = u_v_pairs_to_sr_pairs(u_v_pairs, N, smooth_bound)

    # 6. Update the sr-pairs...
    sr_pairs.update(found_sr_pairs)

    elapsed_time = time.time_ns() - start_time

    print(
        f'In iteration {current_iteration} ({elapsed_time / 10e9:2f} sec)...\n'
        f'Filtered {len(found_sr_pairs)} sr-pairs from {len(u_v_pairs)} u, v pairs\n'
        f'Total sr-pairs gathered so far: {len(sr_pairs)}\n'
    )

print(f'{len(sr_pairs)} sr-pairs found: \n{sr_pairs}\n')

Factoring N = 48567227
with precision parameter (c): 4 and lattice parameter (l): 1

Bit-length (m): 26
Lattice dimension (n): 5
Smooth bound: 50

In iteration 1 (0.001246 sec)...
Filtered 1 sr-pairs from 32 u, v pairs
Total sr-pairs gathered so far: 1

In iteration 2 (0.000644 sec)...
Filtered 2 sr-pairs from 32 u, v pairs
Total sr-pairs gathered so far: 2

In iteration 3 (0.000684 sec)...
Filtered 1 sr-pairs from 32 u, v pairs
Total sr-pairs gathered so far: 3

In iteration 4 (0.000660 sec)...
Filtered 2 sr-pairs from 32 u, v pairs
Total sr-pairs gathered so far: 3

In iteration 5 (0.000865 sec)...
Filtered 2 sr-pairs from 32 u, v pairs
Total sr-pairs gathered so far: 3

In iteration 6 (0.000618 sec)...
Filtered 1 sr-pairs from 32 u, v pairs
Total sr-pairs gathered so far: 3

In iteration 7 (0.000630 sec)...
Filtered 2 sr-pairs from 32 u, v pairs
Total sr-pairs gathered so far: 3

In iteration 8 (0.000639 sec)...
Filtered 1 sr-pairs from 32 u, v pairs
Total sr-pairs gathered so far: 

# Post-processing sr-pairs for Factorisation